
package com.mycompany.views;

import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import javax.swing.BoxLayout;
import javax.swing.JLabel;

/**
 *
 * @author Mario
 */
public class Buscar extends javax.swing.JPanel {

    /**
     * Creates new form Buscar
     */
    public Buscar() {
        initComponents();
         InitStyles();
         Buscar(Principal.rutaArchivo);
    }

    
    private void InitStyles(){
    tituloBuscar.putClientProperty( "FlatLaf.style", "font: 200% $semibold.font" );
    campoID.putClientProperty( "JComponent.roundRect", true );
    tituloUsuarios.putClientProperty( "FlatLaf.styleClass",  "font: 200% $light.font" );
    tituloID.putClientProperty( "FlatLaf.styleClass",  "font: 200% $light.font" );
    btnBuscar.putClientProperty( "JButton.buttonType", "roundRect" );
    }
  
    private void Buscar(String archivo) {
        PanelUsuarios.removeAll(); // Limpiar el panel antes de agregar nuevos datos
        PanelUsuarios.setLayout(new BoxLayout(PanelUsuarios, BoxLayout.Y_AXIS)); // Asegurar formato de lista vertical
        try {
            System.out.println("Intentando abrir archivo: " + archivo);

            RandomAccessFile raf = new RandomAccessFile(archivo, "r"); // Modo lectura
            String linea;
            boolean encontrado = false;
            while ((linea = raf.readLine()) != null) { // Leer línea por línea
                JLabel lbUsuario = new JLabel(linea);
                PanelUsuarios.add(lbUsuario);
            }

            raf.close(); // Cerrar archivo

        } catch (IOException e) {
            System.out.println("Error I/O: " + e.getMessage());

        }
        
    PanelUsuarios.revalidate(); // Refrescar la interfaz
    PanelUsuarios.repaint();
    }

     
   private void Buscar(String archivo, int id) {
    try {
        System.out.println("Intentando abrir archivo: " + archivo);

        RandomAccessFile raf = new RandomAccessFile(archivo, "r"); // Modo lectura
        PanelUsuarios.removeAll(); // Limpiar el panel antes de agregar nuevos datos

        int tamRegistro = 34; // Tamaño fijo del registro
        long pos = (id - 1) * tamRegistro; // Posición exacta del registro en el archivo
        System.out.println("Posición calculada: " + pos);

        if (pos >= raf.length()) { // Verificar si el ID existe en el archivo
            System.out.println("No se encontró el ID: " + id);
            raf.close();
            return;
        }

        raf.seek(pos); // Ir a la posición exacta

        byte[] buffer = new byte[tamRegistro]; 
        raf.readFully(buffer); // Leer exactamente 34 bytes

        String linea = new String(buffer).trim();
        System.out.println("Linea leída: '" + linea + "'");

        // Extraer el ID desde el archivo
        String idLeido = linea.substring(0, 3).trim();
        System.out.println("ID leído: '" + idLeido + "'");
        System.out.println("ID esperado: '" + String.format("%03d", id) + "'");

        if (!idLeido.equals(String.format("%03d", id))) {
            System.out.println("No se encontró el ID: " + id);
            
        } else {
            System.out.println("Coincidencia encontrada: " + linea);
            JLabel lbUsuario = new JLabel(linea);
            PanelUsuarios.add(lbUsuario);//if it is found displayed in the panel on a Jlabel
        }

        raf.close(); //close the file 
    } catch (IOException e) {
        System.out.println("Error I/O: " + e.getMessage());
    }

    PanelUsuarios.revalidate(); // Refresh the interface
    PanelUsuarios.repaint();
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloBuscar = new javax.swing.JLabel();
        texto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PanelUsuarios = new javax.swing.JPanel();
        tituloUsuarios = new javax.swing.JLabel();
        campoID = new javax.swing.JTextField();
        tituloID = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tituloBuscar.setText("Buscar Usuario");

        texto.setText("Se mostrara toda la informacion de los usuarios registrados, si desea uno en particular ingrese su ID.");

        PanelUsuarios.setBackground(new java.awt.Color(204, 204, 204));
        PanelUsuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PanelUsuariosKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout PanelUsuariosLayout = new javax.swing.GroupLayout(PanelUsuarios);
        PanelUsuarios.setLayout(PanelUsuariosLayout);
        PanelUsuariosLayout.setHorizontalGroup(
            PanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );
        PanelUsuariosLayout.setVerticalGroup(
            PanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(PanelUsuarios);

        tituloUsuarios.setText("Usuarios/Usuario");

        campoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIDActionPerformed(evt);
            }
        });

        tituloID.setText("ID");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(texto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(tituloUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tituloID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(tituloBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addComponent(btnBuscar)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIDActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int id = Integer.parseInt(campoID.getText());
        Buscar(Principal.rutaArchivo, id);
        
        
        
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void PanelUsuariosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PanelUsuariosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelUsuariosKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelUsuarios;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JTextField campoID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel texto;
    private javax.swing.JLabel tituloBuscar;
    private javax.swing.JLabel tituloID;
    private javax.swing.JLabel tituloUsuarios;
    // End of variables declaration//GEN-END:variables
}
