
package com.mycompany.views;

import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;

/**
 *
 * @author Mario
 */
public class Eliminar extends javax.swing.JPanel {

    /**
     * Creates new form Eliminar
     */
    public Eliminar() {
        initComponents();
         InitStyles();
    }

    private void InitStyles(){
    tituloEliminar.putClientProperty( "FlatLaf.style", "font: 200% $semibold.font" );
    campoID.putClientProperty( "JComponent.roundRect", true );
    textID.putClientProperty( "FlatLaf.styleClass",  "font: 200% $light.font" );
    btnEliminar.putClientProperty( "JButton.buttonType", "roundRect" );
    }
    
    private void Eliminar(String ruta, int id) {
    File archivoOriginal = new File(ruta);
    File archivoTemporal = new File("temp.txt");

    try {
        RandomAccessFile raf = new RandomAccessFile(archivoOriginal, "r");
        RandomAccessFile tempRaf = new RandomAccessFile(archivoTemporal, "rw");

        int tamRegistro = 34; // Tamaño fijo del registro
        long pos = (id - 1) * tamRegistro; // Posición exacta del registro en el archivo
        boolean encontrado = false;

        if (pos < raf.length()) { // Verificar si el ID existe en el archivo
            raf.seek(pos); // Ir a la posición exacta

            byte[] buffer = new byte[tamRegistro]; 
            raf.readFully(buffer); // Leer exactamente 34 bytes

            String linea = new String(buffer).trim();
            String idLeido = linea.substring(0, 3).trim();

            System.out.println("ID leído: '" + idLeido + "'");
            System.out.println("ID esperado: '" + String.format("%03d", id) + "'");

            if (idLeido.equals(String.format("%03d", id))) {
                encontrado = true; // Se encontró el usuario a eliminar
                System.out.println("Usuario con ID " + id + " encontrado y eliminado.");
            } else {
                // Escribir la línea en el archivo temporal si no coincide el ID
                tempRaf.write(buffer);
            }
        }

        // Copiar el resto del archivo original al temporal
        raf.seek(0);
        for (long i = 0; i < raf.length(); i += tamRegistro) {
            if (i == pos && encontrado) { // Saltar el registro eliminado
                raf.seek(i + tamRegistro);
                continue;
            }
            raf.seek(i);
            byte[] buffer = new byte[tamRegistro];
            raf.readFully(buffer);
            tempRaf.write(buffer);
        }

        raf.close();
        tempRaf.close();

        if (encontrado) {
            // Reemplazar archivo original con el nuevo sin el usuario eliminado
            archivoOriginal.delete();
            archivoTemporal.renameTo(archivoOriginal);
        } else {
            System.out.println("Usuario con ID " + id + " no encontrado.");
            archivoTemporal.delete(); // Eliminar el archivo temporal si no hubo cambios
        }

    } catch (IOException e) {
        System.out.println("Error I/O: " + e.getMessage());
    }
}

    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloEliminar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoID = new javax.swing.JTextField();
        textID = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tituloEliminar.setText("Eliminar Usuario");

        jLabel2.setText("Por favor ingrese el ID del usuario que desea eliminar.");

        campoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIDActionPerformed(evt);
            }
        });

        textID.setText("ID");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(tituloEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 256, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(260, 260, 260))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addGap(329, 329, 329))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(tituloEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(64, 64, 64)
                .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addGap(92, 92, 92))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIDActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Eliminar(Principal.rutaArchivo, Integer.parseInt(campoID.getText()));
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JTextField campoID;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textID;
    private javax.swing.JLabel tituloEliminar;
    // End of variables declaration//GEN-END:variables
}
