
package com.mycompany.views;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.RandomAccessFile;
import java.util.Arrays;
import javax.swing.*;

/**
 *
 * @author Mario
 */

//url 


public class Registro extends javax.swing.JPanel {

    
    
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        InitStyles();
        
    }
    
    private void InitStyles(){
    titleRegisto.putClientProperty( "FlatLaf.style", "font: 200% $semibold.font" );
    textNombre.putClientProperty( "JComponent.roundRect", true );
    textID.putClientProperty( "JComponent.roundRect", true );
    passw.putClientProperty( "JComponent.roundRect", true );
    jLabelCedula.putClientProperty( "FlatLaf.styleClass",  "font: 200% $light.font" );
    jLabelNombre.putClientProperty( "FlatLaf.styleClass",  "font: 200% $light.font" );
    jLabelPassw.putClientProperty( "FlatLaf.styleClass",  "font: 200% $light.font" );
    btnGuardar.putClientProperty( "JButton.buttonType", "roundRect" );
    
    }
private void registrarUsuario(JTextField nombre, JTextField ID, JPasswordField pass, String url) {
    String n = nombre.getText().trim();
    String Id = ID.getText().trim();
    String pasw = new String(pass.getPassword()).trim(); // Obtener contraseña de manera segura

    if (n.isEmpty() || pasw.isEmpty() || Id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    int id;
    try {
        id = Integer.parseInt(Id);
        if (id <= 0) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un número positivo.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El ID debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Formatear los datos con tamaño fijo
    String usuario = String.format("%-15s", n);
    String clave = String.format("%-15s", pasw);
    String nuevoRegistro = String.format("%03d%s%s\n", id, usuario, clave); // ID fijo de 3 caracteres

    int tamRegistro = 34; // Tamaño fijo del registro
    long pos = (id - 1) * tamRegistro; // Posición exacta donde escribir el registro

    try (RandomAccessFile raf = new RandomAccessFile(url, "rw")) {
        if (pos < raf.length()) { // Verificar si el registro ya existe
            raf.seek(pos);
            byte[] buffer = new byte[tamRegistro];
            raf.read(buffer);
            String lineaExistente = new String(buffer).trim();

            if (!lineaExistente.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Error: El ID ya está ocupado.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        raf.seek(pos); // Ir a la posición exacta
        raf.writeBytes(nuevoRegistro); // Escribir el nuevo usuario en su posición fija

        JOptionPane.showMessageDialog(this, "Usuario registrado con éxito.");

        // Limpiar campos después de registrar
        ID.setText("");
        nombre.setText("");
        pass.setText("");

    } catch (IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al guardar el usuario.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgR = new javax.swing.JPanel();
        titleRegisto = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        textID = new javax.swing.JTextField();
        passw = new javax.swing.JPasswordField();
        texto = new javax.swing.JLabel();
        jLabelCedula = new javax.swing.JLabel();
        jLabelPassw = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();

        bgR.setBackground(new java.awt.Color(255, 255, 255));

        titleRegisto.setText("Registro");

        textID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIDActionPerformed(evt);
            }
        });

        passw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwActionPerformed(evt);
            }
        });

        texto.setText("Agregue la informacion del usuario que desea registrar, el ID, Nombre y Contraseña.");

        jLabelCedula.setText("Cedula-ID");

        jLabelPassw.setText("Contraseña");

        jLabelNombre.setText("Nombre");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgRLayout = new javax.swing.GroupLayout(bgR);
        bgR.setLayout(bgRLayout);
        bgRLayout.setHorizontalGroup(
            bgRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgRLayout.createSequentialGroup()
                .addGroup(bgRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgRLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(bgRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNombre)
                            .addComponent(textID)
                            .addComponent(passw)))
                    .addGroup(bgRLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(bgRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPassw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(195, 195, 195))
                    .addGroup(bgRLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(bgRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(bgRLayout.createSequentialGroup()
                                .addComponent(titleRegisto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(104, 104, 104)))
                        .addGap(28, 28, 28)))
                .addGap(224, 224, 224))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgRLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(64, 64, 64))
        );
        bgRLayout.setVerticalGroup(
            bgRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgRLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(titleRegisto, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelPassw, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passw, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnGuardar)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIDActionPerformed

    private void passwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String url = Principal.rutaArchivo;
        System.out.println(url);
        registrarUsuario(textNombre, textID, passw, url);
        
        
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgR;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPassw;
    private javax.swing.JPasswordField passw;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textNombre;
    private javax.swing.JLabel texto;
    private javax.swing.JLabel titleRegisto;
    // End of variables declaration//GEN-END:variables
}
